const businesses = [
    {
        _id: '1',
        businessName: 'Chic Cuts Salon',
        address: '123 Main St',
        state: 'Stateville',
        city: 'Cityville',
        pincode: 123456,
        landmark: 'Near Park',
        businessType: 'Salon',
        openingTime: '09:00',
        closingTime: '20:00',
        offDays: 'Sunday',
        services: [
            {
                serviceName: 'Haircut',
                duration: '30 mins',
                noOfSeats: 5,
                serviceDescription: 'Stylish haircuts and color treatments for a modern look.',
                servicePrice: 50,
            },
            {
                serviceName: 'Hair Color',
                duration: '1 hr',
                noOfSeats: 3,
                serviceDescription: 'Professional hair coloring services.',
                servicePrice: 80,
            },
            {
                serviceName: 'Hair Styling',
                duration: '45 mins',
                noOfSeats: 4,
                serviceDescription: 'Creative and trendy hairstyles for any occasion.',
                servicePrice: 60,
            },
        ],
        contactEmail: 'contact@chiccuts.com',
        contactPhone: '123-456-7890',
        businessLogo: 'https://via.placeholder.com/150?text=Chic+Cuts+Salon',
        businessImages: [
            'https://via.placeholder.com/600x400?text=Chic+Cuts+Salon+1',
            'https://via.placeholder.com/600x400?text=Chic+Cuts+Salon+2',
            'https://via.placeholder.com/600x400?text=Chic+Cuts+Salon+3',
            'https://via.placeholder.com/600x400?text=Chic+Cuts+Salon+4',
        ],
    },
    {
        _id: '2',
        businessName: 'Bright Future Grocery',
        address: '456 Market St',
        state: 'Stateville',
        city: 'Cityville',
        pincode: 654321,
        landmark: 'Opposite Mall',
        businessType: 'Grocery Store',
        openingTime: '08:00',
        closingTime: '22:00',
        offDays: 'None',
        services: [
            {
                serviceName: 'Organic Products',
                duration: 'N/A',
                noOfSeats: 0,
                serviceDescription: 'A well-stocked grocery store offering organic and locally sourced products.',
                servicePrice: 30,
            },
            {
                serviceName: 'Fresh Produce',
                duration: 'N/A',
                noOfSeats: 0,
                serviceDescription: 'Daily fresh fruits and vegetables.',
                servicePrice: 20,
            },
            {
                serviceName: 'Dairy Products',
                duration: 'N/A',
                noOfSeats: 0,
                serviceDescription: 'Wide selection of dairy products including milk, cheese, and yogurt.',
                servicePrice: 25,
            },
        ],
        contactEmail: 'contact@brightfuture.com',
        contactPhone: '987-654-3210',
        businessLogo: 'https://via.placeholder.com/150?text=Bright+Future+Grocery',
        businessImages: [
            'https://via.placeholder.com/600x400?text=Bright+Future+Grocery+1',
            'https://via.placeholder.com/600x400?text=Bright+Future+Grocery+2',
            'https://via.placeholder.com/600x400?text=Bright+Future+Grocery+3',
            'https://via.placeholder.com/600x400?text=Bright+Future+Grocery+4',
        ],
    },
    {
        _id: '3',
        businessName: 'Gourmet Bistro',
        address: '789 Culinary Ave',
        state: 'Gourmet State',
        city: 'Foodtown',
        pincode: 789012,
        landmark: 'Next to the Food Market',
        businessType: 'Restaurant',
        openingTime: '10:00',
        closingTime: '22:00',
        offDays: 'Monday',
        services: [
            {
                serviceName: 'Fine Dining',
                duration: '2 hrs',
                noOfSeats: 40,
                serviceDescription: 'Exquisite meals prepared with the finest ingredients.',
                servicePrice: 100,
            },
            {
                serviceName: 'Lunch Special',
                duration: '1.5 hrs',
                noOfSeats: 40,
                serviceDescription: 'Special lunch menu with seasonal ingredients.',
                servicePrice: 60,
            },
            {
                serviceName: 'Dinner Special',
                duration: '2 hrs',
                noOfSeats: 40,
                serviceDescription: 'Premium dinner options with a selection of wines.',
                servicePrice: 120,
            },
        ],
        contactEmail: 'contact@gourmetbistro.com',
        contactPhone: '456-789-0123',
        businessLogo: 'https://via.placeholder.com/150?text=Gourmet+Bistro',
        businessImages: [
            'https://via.placeholder.com/600x400?text=Gourmet+Bistro+1',
            'https://via.placeholder.com/600x400?text=Gourmet+Bistro+2',
            'https://via.placeholder.com/600x400?text=Gourmet+Bistro+3',
            'https://via.placeholder.com/600x400?text=Gourmet+Bistro+4',
        ],
    },
    {
        _id: '4',
        businessName: 'Tech Haven',
        address: '321 Tech St',
        state: 'Techland',
        city: 'Innovate City',
        pincode: 654987,
        landmark: 'Near the Innovation Hub',
        businessType: 'Electronics Store',
        openingTime: '09:00',
        closingTime: '18:00',
        offDays: 'Saturday',
        services: [
            {
                serviceName: 'Electronics Repair',
                duration: '1 hr',
                noOfSeats: 0,
                serviceDescription: 'Repairs and maintenance for all kinds of electronics.',
                servicePrice: 75,
            },
            {
                serviceName: 'Device Setup',
                duration: '1 hr',
                noOfSeats: 0,
                serviceDescription: 'Setup and configuration of new electronic devices.',
                servicePrice: 50,
            },
            {
                serviceName: 'Software Installation',
                duration: '30 mins',
                noOfSeats: 0,
                serviceDescription: 'Installation of software and applications.',
                servicePrice: 40,
            },
        ],
        contactEmail: 'support@techhaven.com',
        contactPhone: '789-012-3456',
        businessLogo: 'https://via.placeholder.com/150?text=Tech+Haven',
        businessImages: [
            'https://via.placeholder.com/600x400?text=Tech+Haven+1',
            'https://via.placeholder.com/600x400?text=Tech+Haven+2',
            'https://via.placeholder.com/600x400?text=Tech+Haven+3',
            'https://via.placeholder.com/600x400?text=Tech+Haven+4',
        ],
    },
    {
        _id: '5',
        businessName: 'EcoMart',
        address: '654 Greenway',
        state: 'Eco State',
        city: 'Sustainable City',
        pincode: 321456,
        landmark: 'Next to the Green Park',
        businessType: 'Eco-Friendly Store',
        openingTime: '09:00',
        closingTime: '20:00',
        offDays: 'None',
        services: [
            {
                serviceName: 'Eco Products',
                duration: 'N/A',
                noOfSeats: 0,
                serviceDescription: 'A store offering a wide range of eco-friendly and sustainable products.',
                servicePrice: 25,
            },
            {
                serviceName: 'Organic Skincare',
                duration: 'N/A',
                noOfSeats: 0,
                serviceDescription: 'Organic skincare products made from natural ingredients.',
                servicePrice: 40,
            },
            {
                serviceName: 'Reusable Goods',
                duration: 'N/A',
                noOfSeats: 0,
                serviceDescription: 'Reusable and sustainable alternatives to everyday items.',
                servicePrice: 35,
            },
        ],
        contactEmail: 'contact@ecomart.com',
        contactPhone: '012-345-6789',
        businessLogo: 'https://via.placeholder.com/150?text=EcoMart',
        businessImages: [
            'https://via.placeholder.com/600x400?text=EcoMart+1',
            'https://via.placeholder.com/600x400?text=EcoMart+2',
            'https://via.placeholder.com/600x400?text=EcoMart+3',
            'https://via.placeholder.com/600x400?text=EcoMart+4',
        ],
    },
];

export default businesses;
